### PR TITLE
fix: renovate newsletter form style

### LINKED ISSUE #33: [bug]: No border in newsletter form input field
### Description

There is no border in the newsletter form input field. In small devices, the user cannot clearly see the difference between the input form and the subscribe button.

### Screenshots

image

## Expected 
- there should be a light border on input form and subscribe button.

### PR DESCRIPTION
**Pull request by mnamesujit**
## Fixes Issue
Closes #33 

## Changes proposed
- modified page.tsx file

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### Desktop View
image

### Small Screen View:
image

### CODE REVIEW

File: app/(marketing)/page.tsx [hunk 1]
```diff
@@ -130,11 +130,11 @@ export default function Home() {
           </p>
 
           <div className="flex gap-2 md:flex-row flex-col rounded-sm bg-slate-100 md:rounded-full p-2 md:p-1 mt-4 text-black">
-            <Input
+            <input
```
Comment (ManishBisht777) [inline app/(marketing)/page.tsx:133]: can't it be done with Custom input present in `ui/input` like before instead of default input

File: app/(marketing)/page.tsx [hunk 2]
```diff
@@ -130,11 +130,11 @@ export default function Home() {
...
               placeholder="Enter your Email "
-              className="bg-transparent border-none placeholder:text-slate-400 focus-visible:ring-offset-0 focus-visible:ring-0 focus-visible:outline-none"
+              className="bg-transparent border border-slate-300 rounded-full px-4 py-1.5 md:border-none placeholder:text-slate-400 focus-visible:ring-offset-0 focus-visible:ring-0 focus-visible:outline-none"
             />
-            <Button className="rounded-full">Subscribe</Button>
+            <Button className="rounded-full text-white bg-[#020820] hover:bg-[#020832]">Subscribe</Button>
```
Comment (ManishBisht777) [inline app/(marketing)/page.tsx:137]: - there's already a hover effect on the button so you can remove the hover from here
- there is no need to hard code the values you can just use `dark:bg-black` to override the dark mode CSS for just this button

**Review by ManishBisht777 — COMMENTED** [review]
Left some comments

File: app/(marketing)/page.tsx (hunk 1 above)
Comment (mnamesujit) [reply app/(marketing)/page.tsx:133]: okk  wait ...

File: app/(marketing)/page.tsx (hunk 2 above)
Comment (mnamesujit) [reply app/(marketing)/page.tsx:137]: thankyou @ManishBisht777 for correcting me

**Comment by mnamesujit** [comment]
Okk done, Kindly review it again....

**Review by ManishBisht777 — APPROVED** [review]
LGTM

**Comment by ManishBisht777** [comment]
Thanks for the contributionn @mnamesujit 🎉

**Comment by mnamesujit** [comment]
Your Welcome @ManishBisht777
